package internal

import (
	"fmt"
	"strings"
)

type CodeWriter struct {
	indent int
	sb     strings.Builder
}

func NewCodeWriter() *CodeWriter {
	return &CodeWriter{indent: 0, sb: strings.Builder{}}
}

func (g *CodeWriter) write(args ...any) {
	if len(args) == 0 {
		return
	}
	indent := strings.Repeat("    ", g.indent)
	g.sb.WriteString(indent)
	if len(args) > 1 {
		fmt.Fprintf(&g.sb, args[0].(string), args[1:]...) //nolint:forcetypeassert
	} else {
		g.sb.WriteString(args[0].(string)) //nolint:forcetypeassert
	}
	g.sb.WriteString("\n")
}

type Symbol struct {
	Name string
	Reg  string
	Type string
}
type IRScope struct {
	Parent  *IRScope
	Symbols map[string]Symbol
}

func NewIRScope(parent *IRScope) *IRScope {
	return &IRScope{Parent: parent, Symbols: map[string]Symbol{}}
}

func (s *IRScope) Lookup(name string) (Symbol, bool) {
	if s, ok := s.Symbols[name]; ok {
		return s, true
	}
	if s.Parent != nil {
		return s.Parent.Lookup(name)
	}
	return Symbol{}, false
}

func (s *IRScope) Set(name string, value string, typ string) {
	if _, ok := s.Symbols[name]; ok {
		panic(Errorf("symbol %s already defined", name))
	}
	s.Symbols[name] = Symbol{Name: name, Reg: value, Type: typ}
}

type IRGen struct {
	CodeWriter
	env          *TypeEnv
	scope        *IRScope
	regCounter   int
	constCounter int
	strConsts    map[string]string
	astCode      map[ASTID]string
}

func NewIRGen(env *TypeEnv) *IRGen {
	return &IRGen{
		CodeWriter:   *NewCodeWriter(),
		scope:        NewIRScope(nil),
		env:          env,
		regCounter:   1,
		constCounter: 1,
		strConsts:    map[string]string{},
		astCode:      map[ASTID]string{},
	}
}

func (g *IRGen) VisitFile(file *File) {
	g.write("; Generated by metallc")
	g.write("")
	g.write(`source_filename = "%s"`, file.Span.Source.Name)
	g.write("")
	WalkFile(file, g)
	g.write("; Global constants.")
	g.write("")
	for value, reg := range g.strConsts {
		g.write(`%s = private constant [%d x i8] c"%s"`, reg, len(value)+1, value+`\00`)
	}
}

func (g *IRGen) VisitDecl(decl *Decl) {
	WalkDecl(decl, g)
}

func (g *IRGen) VisitType(typ *ASTType) {
	WalkASTType(typ, g)
}

func (g *IRGen) VisitFun(astFun *Fun) {
	typ := g.lookupType(astFun.ID)
	fun := typ.Fun
	binding := g.lookupBinding(astFun.ID)
	isMain := binding.Name == "main"
	ret := g.irType(fun.Return)
	if isMain {
		ret = "i32"
	}
	g.enterScope()
	params := strings.Builder{}
	paramAllocas := strings.Builder{}
	for i, param := range astFun.Params {
		if i > 0 {
			params.WriteString(", ")
		}
		preg := g.reg()
		typ := g.irType(g.lookupType(param.Type.ID))
		params.WriteString(typ)
		params.WriteString(" ")
		params.WriteString(preg)
		areg := g.reg()
		fmt.Fprintf(&paramAllocas, "    %s = alloca %s\n", areg, typ)
		fmt.Fprintf(&paramAllocas, "    store %s %s, ptr %s", typ, preg, areg)
		g.scope.Set(param.Name.Name, areg, typ)
	}
	g.write("define %s @%s(%s) {", ret, binding.Name, params.String())
	if len(astFun.Params) > 0 {
		g.write(paramAllocas.String())
	}
	g.indent += 1
	WalkFun(astFun, g)
	g.leaveScope()
	if isMain {
		g.write("ret i32 0")
	} else {
		lastCode := g.lookupCode(astFun.Block.ID)
		g.write("ret %s %s", g.irType(fun.Return), lastCode)
	}
	g.indent -= 1
	g.write("}\n")
}

func (g *IRGen) VisitFunParam(param *FunParam) {
	WalkFunParam(param, g)
}

func (g *IRGen) VisitBlock(block *Block) {
	g.enterScope()
	WalkBlock(block, g)
	g.leaveScope()
	code := "void"
	if len(block.Exprs) > 0 {
		code = g.lookupCode(block.Exprs[len(block.Exprs)-1].ID())
	}
	g.setCode(block.ID, code)
}

func (g *IRGen) VisitExpr(expr *Expr) {
	WalkExpr(expr, g)
}

func (g *IRGen) VisitAssign(assign *Assign) {
	WalkAssign(assign, g)
	rhs := g.lookupCode(assign.Value.ID())
	symbol, ok := g.scope.Lookup(assign.Ident.Name)
	if !ok {
		panic(Errorf("assign to unknown variable: %s", assign.Ident.Name))
	}
	g.write("store %s %s, ptr %s", symbol.Type, rhs, symbol.Reg)
}

func (g *IRGen) VisitCall(call *Call) {
	WalkCall(call, g)
	typ := g.lookupType(call.Callee.ID())
	if typ.Kind != TypeFun {
		panic(Errorf("callee is not a function"))
	}
	fun := typ.Fun
	sb := strings.Builder{}
	if fun.Return.Kind == TypeVoid {
		g.setCode(call.ID, "void")
	} else {
		reg := g.reg()
		sb.WriteString(reg + " = ")
		g.setCode(call.ID, reg)
	}
	sb.WriteString("call ")
	sb.WriteString(g.irType(fun.Return))
	sb.WriteString(" @")
	sb.WriteString(g.lookupCode(call.Callee.ID()))
	sb.WriteString(" (")
	for i, arg := range call.Args {
		if i > 0 {
			sb.WriteString(", ")
		}
		argType := g.lookupType(arg.ID())
		sb.WriteString(g.irType(argType))
		sb.WriteString(" ")
		argCode := g.lookupCode(arg.ID())
		sb.WriteString(argCode)
	}
	sb.WriteString(")")
	g.write(sb.String())
}

func (g *IRGen) VisitIdent(ident *Ident) {
	if symbol, ok := g.scope.Lookup(ident.Name); ok {
		ptrreg := g.reg()
		g.write("%s = load %s, ptr %s", ptrreg, symbol.Type, symbol.Reg)
		g.setCode(ident.ID, ptrreg)
		return
	}
	g.setCode(ident.ID, ident.Name)
}

func (g *IRGen) VisitName(name *Name) {
	g.setCode(name.ID, name.Name)
}

func (g *IRGen) VisitIntExpr(int_ *IntExpr) {
	g.setCode(int_.ID, "%d", int_.Value)
}

func (g *IRGen) VisitStringExpr(str *StringExpr) {
	creg, ok := g.strConsts[str.Value]
	if !ok {
		creg = g.creg()
		g.strConsts[str.Value] = creg
	}
	reg := g.reg()
	g.write("%s = getelementptr [%d x i8], ptr %s, i32 0, i32 0", reg, len(str.Value)+1, creg)
	g.setCode(str.ID, reg)
}

func (g *IRGen) VisitVar(var_ *Var) {
	WalkVar(var_, g)
	// We are a bit lazy here and just use an `alloca` instruction.
	// LLVM will optimize this.
	reg := g.reg()
	typ := g.irType(g.lookupType(var_.Init.ID()))
	expr := g.lookupCode(var_.Init.ID())
	g.write("%s = alloca %s", reg, typ)
	g.write("store %s %s, ptr %s", typ, expr, reg)
	g.setCode(var_.ID, reg)
	g.scope.Set(var_.Name.Name, reg, typ)
}

func (g *IRGen) enterScope() {
	g.scope = NewIRScope(g.scope)
}

func (g *IRGen) leaveScope() {
	g.scope = g.scope.Parent
}

func (g *IRGen) reg() string {
	id := g.regCounter
	g.regCounter++
	return fmt.Sprintf("%%r%d", id)
}

func (g *IRGen) creg() string {
	id := g.constCounter
	g.constCounter++
	return fmt.Sprintf("@%d", id)
}

func (g *IRGen) irType(typ Type) string {
	switch typ.Kind {
	case TypeInt:
		return "i64"
	case TypeStr:
		return "ptr"
	case TypeVoid:
		return "void"
	case TypeFun:
		panic("unexpected fun type")
	default:
		panic(Errorf("unknown type kind: %d", typ.Kind))
	}
}

func (g *IRGen) setCode(astID ASTID, code string, args ...any) {
	if _, ok := g.astCode[astID]; ok {
		panic(Errorf("code  already set for AST node %d", astID))
	}
	if len(args) > 0 {
		code = fmt.Sprintf(code, args...)
	}
	g.astCode[astID] = code
}

func (g *IRGen) lookupCode(astID ASTID) string {
	code, ok := g.astCode[astID]
	if !ok {
		panic(Errorf("no reg for AST node %d", astID))
	}
	return code
}

func (g *IRGen) lookupBinding(astID ASTID) Binding {
	b, ok := g.env.Bindings[astID]
	if !ok {
		panic(Errorf("no binding for AST node %d", astID))
	}
	return b
}

func (g *IRGen) lookupType(astID ASTID) Type {
	typ, ok := g.env.Types[astID]
	if !ok {
		panic(Errorf("no type for AST node %d", astID))
	}
	return typ
}

func GenIR(file *File, typeEnv *TypeEnv) (string, error) {
	g := NewIRGen(typeEnv)
	g.VisitFile(file)
	g.write(builtins)
	return g.sb.String(), nil
}

const builtins = `
; >>> Runtime

;     External functions.
declare i32 @puts(ptr)
declare i32 @printf(ptr, ...)

;      Builtin functions.
define void @print_str(ptr %s) {
    call i32 @puts(ptr %s)
    ret void
}

@fmt_int = private constant [4 x i8] c"%d\0A\00"
define void @print_int(i64 %n) {
    call i32 (ptr, ...) @printf(ptr @fmt_int, i64 %n)
    ret void
}
`
